Data Analysis - Assignement 2
========================================================

Introduction
------------

Based on the "Human Activity Recognition Using Smartphones Data Set" (1), we want to build a predictive model which activity a Samsung phone user is performing, based on factors available in the dataset.


Methods
-------




Activities are the following 
1 WALKING
2 WALKING_UPSTAIRS
3 WALKING_DOWNSTAIRS
4 SITTING
5 STANDING
6 LAYING

This dataset includes ```{r} dim(samsungData)[1]``` measurements and 561 variables


http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

All of the columns of the data set (except the last two) represents one measurement from the Samsung phone. The variable subject indicates which subject was performing the tasks when the measurements were taken. The variable activity tells what activity they were performing. 

Data arre provided. We select only raw data, exclusding...
Subject , actovity

We define our error rate as follow

Datat have been split equally in 3 datasets: training, test, and validation. we select ed specific subject for the training and test set in order to avoid.

Apart subject and activity, the following features have been select from the training dataset.

A predictive function if the following, with

Cross-validatation has been performed on the training set with a K-fold...

Applying the 
7. If no validation - apply 1x to test set
8. If validation - apply to test set and refine
9. If validation - apply 1x to validation


Data Set Information:

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain. 


Attribute Information:

For each record in the dataset it is provided: 
- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration. 
- Triaxial Angular velocity from the gyroscope. 
- A 561-feature vector with time and frequency domain variables. 
- Its activity label. 
- An identifier of the subject who carried out the experiment.

We created a training data set consisting of half of the subjects and a test dataset consisting if the secoind half, The training dataset included subject: 1, 3, 5, and 6.  
The test dataset includes  subjects 27, 28, 29, and 30. 


Results
-------

The Human Activity Recognition database has been built from the recordings of 30 subjects performing activities of daily living (ADL) while carrying a waist-mounted smartphone with embedded inertial sensors.

Conclusion
----------

Form the measeaument included in the dataset [1] from D. Anguita and all, we have built a model that preditc the extivuty a user is doing with an uncertitude of...

```{r fig.width=7, fig.height=6}

```


References
----------

[1] Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine. International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012



Becker, R. A., Chambers, J. M. and Wilks, A. R. (1988) The New S Language. Wadsworth & Brooks/Cole.

R Development Core Team (2009a). R Data Import/Export. Version 2.9.1
(2009-06-26), URL http://cran.r-project.org/manuals/R-data.pdf.
R Development Core Team (2009b). R Installation and Administration.
URL http://cran.r-project.org/doc/manuals/R-admin.pdf.
R Development Core Team (2010). R: A Language and Environment for
Statistical Computing. R Foundation for Statistical Computing, Vienna,
Austria. ISBN 3-900051-07-0, URL http://www.R-project.org.


Disclaimer
==========
Use of the dataset used in the work is acknowledged by referencing publication [1], as specified by its authors (Jorge L. Reyes-Ortiz, Alessandro Ghio, Luca Oneto, Davide Anguita. November 2012). From the dataset authors: "This dataset is distributed AS-IS and no responsibility implied or explicit can be addressed to the authors or their institutions for its use or misuse. Any commercial use is prohibited.".
